const paths = {
  index: "/",
  doctors: "/doctors",
  login: "/login",
  medkit: "/medkit",
  register: "/register",
 
  doctorshome: "/doctorshome",
  pharmacyhome: "/pharmacyhome",
  doctorview: "/doctorview",
  cart: "/cart",
  about: "/about",
  recordpolicy: "/recordpolicy",
  privacypolicy: "/privacypolicy",
  termscondition: "/termscondition",
  cookiespolicy: "/cookiespolicy",
  productview: "/product/:id",
  footer: "/footer",
  checkout: "/checkout",

  common: {
    // appointments: "/appointments",
    // ewallet: "/e-wallet",
    dashboard: "/dashboard",
    history: "/history",
    products: "/products",
    product: "/products/:id",
    messages: "/messages",
    cart: "/shopping-cart",
  },
  patient: {
    orders: "/orders",
    vitals: "/vitals",
    appointments: "/appointments",
    patientmessages: "/patientmessages",
    patientshistory: "/patientshistory",
    patientsorders: "/patientsorders",
    history: "/history",
    messages: "/messages",
    productspatients: "/productspatients",
    checkout: "/patientcheckout",
  },
  doctor: {
    patients: "/patients",
  },
  admin: {
    doctors: "/admin/doctors",
    patients: "/admin/patients",
    products: "/admin/products",
    orders: "/admin/orders",
    history: "/admin/history",
    messages: "/admin/messages",
    message: "/admin/message",
    medkit: "/admin/medkit",
    // ewallet: "/admin/ewallet",
  },
};

export default paths;
